
export default {
  appVersion: '2.0.0',
  dslVersion: '2.0.0',
  configFile: 'config',
  dslPath: 'dsl/',
  dsl: {
    dictionary: 'dictionary/',
    platformdictionary: 'dictionary.json',
    properties: 'properties.json',
    menu: 'menu.json',
    subdomain: 'subdomain/',
    entity: 'entity/',
    service: 'service/',
    bpm: 'general/',
    excel: 'general/exceldata/',
    dependencies: 'package.json',
    lib: 'lib/',
    quickStart: '/node_modules/mx-framework/src/bin/quickStart.js',
    data: 'data/',
    dataset: 'dataset/',
    datasetdsmeta: 'dsmeta.json',
  },
  icon: 'http://at.alicdn.com/t/font_267551_da8k5i.js',
};
