
// global
export const APP_INIT = 'APP_INIT';
export const APP_INIT_END = 'APP_INIT_END';
export const APP_RESIZE = 'APP_RESIZE';
export const APP_LOADING_START = 'APP_LOADING_START';
export const APP_LOADING_END = 'APP_LOADING_END';
export const APP_UPDATE_DSLPATH = 'APP_UPDATE_DSLPATH';
export const APP_UPDATE_GITPATH = 'APP_UPDATE_GITPATH';
export const APP_GIT_MESSAGE = 'APP_GIT_MESSAGE';
export const APP_UPDATE_HOST = 'APP_UPDATE_HOST';

// menu

// tabs
export const TAB_NEW = 'TAB_NEW';
export const TAB_CHANGE = 'TAB_CHANGE';
export const TAB_UPDATE = 'TAB_UPDATE';
export const TAB_REMOVE = 'TAB_REMOVE';

// subdomain
export const SUBDOMAIN_ADD = 'SUBDOMAIN_ADD';
export const SUBDOMAIN_UPDATE = 'SUBDOMAIN_UPDATE';
export const SUBDOMAIN_DELETE = 'SUBDOMAIN_DELETE';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const SERVICE_DEPENDENCIES_UPDATE = 'SERVICE_DEPENDENCIES_UPDATE';
export const SUBDOMAIN_CREATE_SHOW = 'SUBDOMAIN_CREATE_SHOW';
export const SUBDOMAIN_CREATE_CANCEL = 'SUBDOMAIN_CREATE_CANCEL';

// entity
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_ENTITYSUBDOMAIN_UPDATE = 'ENTITY_ENTITYSUBDOMAIN_UPDATE';
export const ENTITY_RELATEDENTITY_UPDATE = 'ENTITY_RELATEDENTITY_UPDATE';
export const ENTITY_RELATEDSERVICE_UPDATE = 'ENTITY_RELATEDSERVICE_UPDATE';
export const ENTITY_PROPERTIES_UPDATE = 'ENTITY_PROPERTIES_UPDATE';
export const ENTITY_RELATED_UPDATE = 'ENTITY_RELATED_UPDATE';
export const ENTITY_CREATE_SHOW = 'ENTITY_CREATE_SHOW';
export const ENTITY_CREATE_CANCEL = 'ENTITY_CREATE_CANCEL';
export const ENTITY_DELETE = 'ENTITY_DELETE';

// service
export const SERVICE_FUNCTIONS_UPDATE = 'SERVICE_FUNCTIONS_UPDATE';
export const SERVICE_ADD = 'SERVICE_ADD';
export const SERVICE_UPDATE = 'SERVICE_UPDATE';
export const SERVICE_DELETE = 'SERVICE_DELETE';
export const SERVICE_FILES_UPDATE = 'SERVICE_FILES_UPDATE';
export const SERVICE_CREATE_SHOW = 'SERVICE_CREATE_SHOW';
export const SERVICE_CREATE_CANCEL = 'SERVICE_CREATE_CANCEL';
// export const SERVICE_FILE_DELETE = 'SERVICE_FILE_DELETE';
// export const SERVICE_FILE_ADD = 'SERVICE_FILE_ADD';

// bpm
export const BPM_UPDATE = 'BPM_ITEM_UPDATE';

// createExcel
export const EXCEL_ADD = 'EXCEL_ADD';

// templatepage
export const TEMPLATEPAGE_UPDATE = 'TEMPLATEPAGE_UPDATE';

// dependencies
export const PACKAGE_UPDATE = 'PACKAGE_UPDATE';
